trigger:
  batch: true
  branches:
    include:
    - '*'

variables:
  artifactName: 'enigmatry-entry-blueprint-template'
  dbContextName: 'BlueprintContext'
  isRelease: $[startsWith(variables['Build.SourceBranch'], 'refs/heads/releases/')]
  majorMinorVersion: 1.0
  nodeVersion: '16.20.2'
  projectNameAngularApp: enigmatry-entry-blueprint-app
  projectNamePrefix: Enigmatry.Entry.Blueprint

# This determines the build number
name: $(majorMinorVersion)$(Rev:.r)

resources:
  repositories:
    - repository: templates
      type: git
      name: Enigmatry - Azure Pipelines Templates/enigmatry-azure-pipelines-templates

stages:
- stage: 'ci_build'
  displayName: 'Build the web application'
  jobs: 
  - job: build_prerequisites
    displayName: Get the prerequisites for the build
    steps:
    - bash: |
        HASH=$(git rev-parse --short $BUILD_SOURCEVERSION)
        VERSION=$BUILD_BUILDNUMBER-$HASH
      
        echo "Hash: $HASH. Setting build number to: $VERSION"
        echo '##vso[build.updatebuildnumber]'$VERSION
      displayName: 'Set Build number'

  - template: build-angular-app-job.yml@templates
    parameters:
      displayName: 'Build Angular App'
      nodeVersion: $(nodeVersion)
      projectNameAngularApp: $(projectNameAngularApp)
  
  - template: build-dotnet-api-job.yml@templates
    parameters:
      artifactName: $(artifactName)
      displayName: 'Build .net API'
      projectNamePrefix: $(projectNamePrefix)

- stage: 'Deploy_Test'
  displayName: 'Deploy to the test environment'
  dependsOn: ci_build
  jobs:
  - template: deploy-to-stage.yml
    parameters:
      environment: test
      migrationConnectionString: $(MigrationConnectionString_Test)
      serviceConnection: 'Enigmatry - Entry Template (Test)'
      webAppName: enigmatry-entry-blueprint-test-001
      webJobWebAppName: enigmatry-entry-blueprint-scheduler-test-001
