parameters:
- name: environment
- name: serviceConnection
  
jobs:
- template: take-web-app-offline.yml@templates
  parameters:
    jobName: 'take_web_app_offline'
    displayName: 'Take Web App offline'
    environment: ${{ parameters.environment }}
    subscription: ${{ parameters.serviceConnection }}
    webAppName: $(webAppName)

- template: take-web-app-offline.yml@templates
  parameters:
    jobName: 'take_scheduler_offline'
    displayName: 'Take Scheduler offline'
    environment: ${{ parameters.environment }}
    subscription: ${{ parameters.serviceConnection }}
    webAppName: $(schedulerWebAppName)

- template: update-database-job.yml@templates
  parameters:
    dbContextName: $(dbContextName)
    displayName: 'Update the database'
    dependsOn:
    - take_web_app_offline
    - take_scheduler_offline
    environment: ${{ parameters.environment }}
    migrationConnectionString: $(migrationConnectionString)

- template: deploy-web-app.yml@templates
  parameters:
    jobName: 'deploy_scheduler'
    artifactName: $(artifactName)
    displayName: Deploy the Scheduler Web Job
    environment: ${{ parameters.environment }}
    packageName: $(projectNamePrefix).Scheduler
    subscription: ${{ parameters.serviceConnection }}
    webAppName: $(schedulerWebAppName)
    publishProfilePostfix: scheduler
    excludeFilesFromAppDataFlag: false

- template: deploy-web-app.yml@templates
  parameters:
    jobName: 'deploy_web_app'
    artifactName: $(artifactName)
    displayName: Deploy the Web app
    dependsOn:
      - deploy_scheduler #must be after scheduler since they are deployed into same webApp (this is Blueprint specific only)
    environment: ${{ parameters.environment }}
    packageName: $(projectNamePrefix).Api
    subscription: ${{ parameters.serviceConnection }}
    webAppName: $(webAppName)
    publishProfilePostfix: new

- job: git_tag
  displayName: Create Git tag
  dependsOn:
  - deploy_web_app
  - deploy_scheduler
  steps:
    - checkout: self
      displayName: 'Checkout current repo'
      persistCredentials: true
    - task: Bash@3
      displayName: Create Git tag
      inputs:
        targetType: 'inline'
        script: |
          git tag ${{ parameters.environment }}-$(Build.SourceBranchName)-$(Build.BuildNumber)
          git push origin ${{ parameters.environment }}-$(Build.SourceBranchName)-$(Build.BuildNumber)